#%RAML 1.0 NamedExample
value:
  - 
    Apellido: "López"
    Nombre: "Juan"
    Dni: "34110032"
    Email: "ju@gmail.com"
    Edad: 34
    Genero: "Masculino"
  - 
    Apellido: "Torres"
    Nombre: "Leonardo"
    Dni: "30210032"
    Email: "le@gmail.com"
    Edad: 40
    Genero: "Masculino"
